name: GitHub - FrutBits Indonesia - Staff List Readme
description: Updates README with the FrutBits Indonesia staff list. Fetched from https://api.frutbits.org/membership
author: frutbits

branding:
  color: yellow
  icon: activity

runs:
  using: node16
  main: dist/index.js