name: GitHub - Zhycorp - Staff List Readme
description: Updates README with the Zhycorp staff list. Fetched from https://api.zhycorp.org/membership
author: zhycorp

branding:
  color: yellow
  icon: activity

runs:
  using: node16
  main: dist/index.js